### ISSUE TITLE
save_path is not a valid checkpoint

### ISSUE THREAD

**Issue by ghost** [vBaiCai/vc_tacotron#2]
Hi
Do you know what can cause this?

`./eval.sh`

```
Traceback (most recent call last):
  File "eval.py", line 50, in <module>
    main()
  File "eval.py", line 46, in main
    run_eval(args)
  File "eval.py", line 32, in run_eval
    synth.load(args.checkpoint)
  File "/Users/poule/dev/voice_conversion/vc_tacotron/synthesizer.py", line 26, in load
    saver.restore(self.session, checkpoint_path)
  File "/Users/poule/.local/share/virtualenvs/vc_tacotron-hdXQUhNx/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1268, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: ./logs-tacotron/model.ckpt-22000
```

**Comment by vBaiCai** [comment]
Do you have a checkpoint named `model.ckpt-22000` under path `./logs-tacotron`?

**Comment by ghost** [comment]
no, how can I get one?

**Comment by vBaiCai** [comment]
You should download and preprocess the data. Then train the model to get checkpoints.

**Comment by ghost** [comment]
I executed all the commands shown in the README
